### ISSUE TITLE
Handling reserved characters in property names

### ISSUE THREAD

**Issue by marcusoftnet** [marcusoftnet/SpecFlow.Assist.Dynamic#11]
A question was raised at [StackOverflow](http://stackoverflow.com/questions/33295455/accessing-properties-with-special-characters-using-specflow-assist-dynamic). 

Right now the tool crashes when you use a C# reserved char like `*&()` etc. 

I've been thinking quite a bit about this but this is my current idea:

* Let this be a setting, that is turned off by default. 
* Turned off means that it crashes with a nice error message
* Turned on the setting replaces all non-letters, non-numbers and non-underscore with an underscore. `CC $ Portion Total` will become `CC_PortionTotal` and `A $trange *Title(causes problems)` will become `A_trange_Title_causesproblems_`

I think this is cleaner and easier to understand than to try to convert all `$` into `S` or `(` into space for example. 

An alternative would to simply remove the char all together, but that might cause problems for comparisons etc. This idea will at least keep the positional order.

**Comment by marcusoftnet** [comment]
Ok, after talking this over with @darrencauthon I think I will do the simplest possible thing for now; just strip the reserved chars out. 

Here's two scenarios that describes the functionality:

```cucumber
Scenario: Using reserved C# characters in column names
	When I create a dynamic instance from this table
		| C$harp n@me (with strange chars) |
		| A value | 
	Then the CharpNmeWithStrangeChars property should equal 'A value'

Scenario: Only alfa numeric characters, plus underscore is allowed in variable names
       When I create a dynamic instance from this table
		| My_Nice_Variable | My $$ Variable (needs clean up) |
		| A value |  Another value |
	Then the My_Nice_Variable property should equal 'A value'
           And the MyVariableNeedsCleanUp property should equal 'Another value'

Scenario: Using only reserved C# characters in column names
	When I create a dynamic instance from this table
		| $@() |
		| A value | 
	Then an exception with a nice error message should be thrown
```

I will not do the configuration, since this feature is just how the tool behaves. It will go into the documentation instead.

**Comment by marcusoftnet** [comment]
Here's some C-sharp to do the replacement stuff:

```csharp
using System.Text.RegularExpressions;
string pattern = @"[^a-zA-Z0-9_]";
string replacement = "";
string input = "%§@@@@m";
string result = Regex.Replace(input, pattern, replacement);
Console.WriteLine(result);
```

**Comment by marcusoftnet** [comment]
Feature documented here https://github.com/marcusoftnet/SpecFlow.Assist.Dynamic/wiki/Conventions-used

**Comment by darrencauthon** [comment]
Good work!

**Comment by marcusoftnet** [comment]
Thanks Darren!
And thanks for the help.

Fun fact; wrote it from a hospital bed (nasty kidney infection).
First time for me :)

**Comment by darrencauthon** [comment]
Hope you get out of there soon. 

Programming puts a silver lining in any down time! So long as we can think and move our fingers, we can be productive. :)

**Comment by marcusoftnet** [comment]
Word!

I'm ok. Get out on Friday. Long IV treatment. That's the reason I'm here.
